MvcApplication21/Controllers/uploadController.cs
using MvcApplication21.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication21.Controllers
{
    public class uploadController : Controller
    {
        //
        // GET: /upload/
        uploadEntities1 db = new uploadEntities1();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Business()
        {
            ViewBag.BusinessCategory = new SelectList(db.BusinessSubcategories, "Id", "SubcategoryName");
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Business(Business t, HttpPostedFileBase file)
        {

            if (file != null)
            {
                int MaxContentLength = 1024 * 1024 * 60; //60 MB
                string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf", ".wmv", ".mp4", ".mp3", ".wav", "mpeg", ".wma" };

                if (!AllowedFileExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                {
                    // ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions));
                    ViewBag.Message = "Please file of type: " + string.Join(", ", AllowedFileExtensions);
                }

                else if (file.ContentLength > MaxContentLength)
                {
                    return Content("Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                }
                else
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Upload/Business"), fileName);


                    file.SaveAs(path);
                    ModelState.Clear();
                    ViewBag.Message = "File uploaded successfully";
                    string ds = file.FileName.Substring(file.FileName.Length - 3);
                    string p = string.Empty;
                    p = Server.MapPath("~/Content/Upload/Business");
                    file.SaveAs(p + file.FileName);

                    using (db)
                    {

                        t.file = file.FileName;
                        db.Businesses.Add(t);
                        db.SaveChanges();

                    }

                }

            }
            else
            {
                return Content("Upload Your file to Continue");
            }
            return RedirectToAction("Index");
        }

         public ActionResult Finance()
        {
            ViewBag.FinanceCategory = new SelectList(db.FinanceSubcategories, "Id", "SubcategoryName");
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Finance(Finance t, HttpPostedFileBase file)
        {

            if (file != null)
            {
                int MaxContentLength = 1024 * 1024 * 60; //60 MB
                string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf", ".html", ".htm", ".wmv", ".mp4", ".mp3", ".wav" };

                if (!AllowedFileExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                {
                    // ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions));
                    ViewBag.Message = "Please file of type: " + string.Join(", ", AllowedFileExtensions);
                }

                else if (file.ContentLength > MaxContentLength)
                {
                    return Content("Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                }
                else
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Upload/Finance"), fileName);


                    file.SaveAs(path);
                    ModelState.Clear();
                    ViewBag.Message = "File uploaded successfully";
                    string ds = file.FileName.Substring(file.FileName.Length - 3);
                    string p = string.Empty;
                    p = Server.MapPath("~/Content/Upload/Finance");
                    file.SaveAs(p + file.FileName);

                    using (db)
                    {

                        t.file = file.FileName;
                        db.Finances.Add(t);
                        db.SaveChanges();

                    }

                }

            }
            else
            {
                return Content("Upload Your file to Continue");
            }
            return RedirectToAction("Index");
        }

        // News Upload 

        public ActionResult News()
        {
            ViewBag.NewsCategory = new SelectList(db.NewsSubcategories, "Id", "SubcategoryName");
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult News(News t, HttpPostedFileBase file)
        {

            if (file != null)
            {
                int MaxContentLength = 1024 * 1024 * 60; //60 MB
                string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf", ".html", ".htm", ".wmv", ".mp4", ".mp3", ".wav" };

                if (!AllowedFileExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                {
                    // ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions));
                    ViewBag.Message = "Please file of type: " + string.Join(", ", AllowedFileExtensions);
                }

                else if (file.ContentLength > MaxContentLength)
                {
                    return Content("Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                }
                else
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Upload/News"), fileName);


                    file.SaveAs(path);
                    ModelState.Clear();
                    ViewBag.Message = "File uploaded successfully";
                    string ds = file.FileName.Substring(file.FileName.Length - 3);
                    string p = string.Empty;
                    p = Server.MapPath("~/Content/Upload/News");
                    file.SaveAs(p + file.FileName);

                    using (db)
                    {

                        t.file = file.FileName;
                        db.News.Add(t);
                        db.SaveChanges();

                    }

                }

            }
            else
            {
                return Content("Upload Your file to Continue");
            }
            return RedirectToAction("Index");
        }
    }
}

MvcApplication21/Views/upload/Business.cshtml
@model MvcApplication21.Business

@{
    ViewBag.Title = "Business";
}

<h2>Business</h2>

@using (Html.BeginForm("Business", "upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Business</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            <input type="file" name="file" />
            @Html.ValidationMessageFor(model => model.file)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubcategoryId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(p => p.SubcategoryId, ViewBag.BusinessCategory as SelectList, "Select category of file", new { id = "SubcategoryId" })
            @Html.ValidationMessageFor(model => model.SubcategoryId)
        </div>


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication21/Views/upload/Finance.cshtml
@model MvcApplication21.Finance

@{
    ViewBag.Title = "Finance";
}

<h2>Upload your Finance News Here</h2>

@using (Html.BeginForm("Finance", "upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Business</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            <input type="file" name="file" />
            @Html.ValidationMessageFor(model => model.file)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubcategoryId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(p => p.SubcategoryId, ViewBag.FinanceCategory as SelectList, "Select category of file", new { id = "SubcategoryId" })
            @Html.ValidationMessageFor(model => model.SubcategoryId)
        </div>


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}